name: Leaderboard

on:
  push:
    branches:
      - main

jobs:
  leaderboard:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker://ghcr.io/actions/leaderboard@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.repository }}
          path: README.md
